### ISSUE TITLE
Intermittently Errno::ENOENT errors

### ISSUE THREAD

**Issue by f1sherman** [rubyatscale/code_ownership#98]
We intermittently (a few times a week) see `Errno::ENOENT` errors when calling `CodeOwnership.for_file` where code ownership claims that a file we're looking up ownership for doesn't exist. It happens for different paths, not always the same path. There doesn't seem to be any obvious pattern for when this happens. The file exists and is found on 99.9% of requests. I've included the gem-specific portion of the trace below. Any ideas on how to track this down? For now we've added a `begin`/`rescue` block around it, but obviously that's not an ideal solution. It's really weird given that I can pass a path that definitely doesn't exist to `CodeOwnership.for_file` and it doesn't error, just returns `nil`.

The error has the signature `Errno::ENOENT: No such file or directory @ rb_sysopen - path/to/file/that/exists.rb`.

```
/app/vendor/bundle/ruby/3.3.0/gems/code_ownership-1.36.2/lib/code_ownership/private/ownership_mappers/file_annotations.rb:86:in `foreach'
,
/app/vendor/bundle/ruby/3.3.0/gems/code_ownership-1.36.2/lib/code_ownership/private/ownership_mappers/file_annotations.rb:86:in `each'
,
/app/vendor/bundle/ruby/3.3.0/gems/code_ownership-1.36.2/lib/code_ownership/private/ownership_mappers/file_annotations.rb:86:in `first'
,

/app/vendor/bundle/ruby/3.3.0/gems/code_ownership-1.36.2/lib/code_ownership/private/ownership_mappers/file_annotations.rb:86:in `file_annotation_based_owner'
,
/app/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11372/lib/types/private/methods/call_validation_2_7.rb:968:in `bind_call'
,
/app/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11372/lib/types/private/methods/call_validation_2_7.rb:968:in `block in create_validator_method_medium1'
,
/app/vendor/bundle/ruby/3.3.0/gems/code_ownership-1.36.2/lib/code_ownership/private/ownership_mappers/file_annotations.rb:29:in `map_file_to_owner'
,
/app/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11372/lib/types/private/methods/call_validation_2_7.rb:968:in `bind_call'
,
/app/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11372/lib/types/private/methods/call_validation_2_7.rb:968:in `block in create_validator_method_medium1'
,
/app/vendor/bundle/ruby/3.3.0/gems/code_ownership-1.36.2/lib/code_ownership.rb:41:in `block in for_file'
,
/app/vendor/bundle/ruby/3.3.0/gems/code_ownership-1.36.2/lib/code_ownership.rb:40:in `each'
,
/app/vendor/bundle/ruby/3.3.0/gems/code_ownership-1.36.2/lib/code_ownership.rb:40:in `for_file'
,
/app/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11372/lib/types/private/methods/call_validation_2_7.rb:968:in `bind_call'
,
/app/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11372/lib/types/private/methods/call_validation_2_7.rb:968:in `block in create_validator_method_medium1'
```

**Comment by tstannard** [comment]
Hi Brian! 

It looks like the Errno::ENOENT error you are getting is indicating a file does not exist even though you can see it in your directory.  

This also seems weird since on [line 78](https://github.com/rubyatscale/code_ownership/blob/40afe763624fc7a8f19f1135f4d0dcaae9cc4644/lib/code_ownership/private/ownership_mappers/file_annotations.rb#L78) we check that the file exists: `return unless File.file?(filename)` 

Do you think there is something in the background that is moving or renaming files?

**Comment by f1sherman** [comment]
Yes it is super weird. I can't think of anything that would move or rename files, and we don't see anything like this anywhere else in our error monitoring. Any tips on how we could troubleshoot it?

**Comment by ashleywillard** [comment]
Hi @f1sherman! I want to check in and see if you're still experiencing this issue. Recently, one of the folks on our team made some improvements to this repo, and those changes may or may not impact this issue. We haven't been able to reproduce this issue, but we'll continue to keep an eye out for it.

**Comment by f1sherman** [comment]
@ashleywillard thanks for the heads up! I haven't seen this crop up in at least 2 weeks. I'll try removing our code that swallows the error and report back here if it comes back. Thank you!

**Comment by f1sherman** [comment]
@ashleywillard unfortunately this error came back after I removed our patch :(.

**Comment by ashleywillard** [comment]
Darn! We still have yet to see this error but I will let you know if we do. It seems like this issue might be tricky to reproduce on our end.

**Comment by timlkelly** [comment]
I recently started experiencing this issue as well. It happened when I reorganized some of our internal gems within our mono-repo. We haven't had this problem at all previously. 

When it started, we had CodeOwnership on version `1.36.2`, and I upgraded to `1.38.3`, but the error persisted. It seems intermittent but happens at least once a day on weekdays, and I've seen as many as seven errors in a single day. I'm assuming the lower weekend traffic is why I see zero or only one error on Saturday/Sunday. 

Is there anything you might recommend to look into to help debug?

**Comment by martinemde** [comment]
Hi @f1sherman and @timlkelly,

Are you seeing these errors on CI builds? In containers? The list of reasons why we'd see an ENOENT for a file that _does_ exist, but for different files each time, is a pretty small set of possible causes (race conditions, filesystem IO problems, etc).

Are the files that are raising ones that you would expect to have annotations?

We pushed #121 to solve this by rescuing for now since it's hard to diagnose exactly why this is happening.

**Comment by f1sherman** [comment]
I have not seen it in CI, only in running Kubernetes pods in Production.

**Comment by timlkelly** [comment]
Same, I have not seen this in CI. Only in production, also Kubernetes pods.

Do you mean the [File Annotation ownership](https://github.com/rubyatscale/code_ownership?tab=readme-ov-file#file-annotation-based-ownership)? No, the files I've seen so far in the error reports are [Package-based Ownership](https://github.com/rubyatscale/code_ownership?tab=readme-ov-file#package-based-ownership).
